codecov:
  require_ci_to_pass: false
  ci:
    - jenkins.flatironinstitute.org

coverage:
  status:
    project:
      default:
        informational: true
        threshold: 100%
        target: 0%
    patch:
      default:
        informational: true
        threshold: 100%
        target: 0%

comment:
  layout: "diff, files"
  behavior: once
  require_changes: true
